import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  CircuitBoardIcon,
  Command,
  CreditCard,
  Calendar,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  LayoutDashboardIcon,
  Loader2,
  LogIn,
  LucideIcon,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  User,
  User2Icon,
  UserX2Icon,
  X,
  PenTool
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  Dashboard: LayoutDashboardIcon,
  Logo: Command,
  Login: LogIn,
  Close: X,
  Profile: User2Icon,
  Spinner: Loader2,
  Kanban: CircuitBoardIcon,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  Trash,
  Employee: UserX2Icon,
  Post: FileText,
  Page: File,
  Media: Image,
  Settings: Settings,
  Billing: CreditCard,
  Ellipsis: MoreVertical,
  Add: Plus,
  Warning: AlertTriangle,
  User,
  ArrowRight,
  Help: HelpCircle,
  Pizza,
  Sun: SunMedium,
  Moon,
  Laptop,
  Calendar,
  Check,
  PenTool
};
